import createClient, { Client } from 'openapi-fetch';
import type { paths } from './truefinals-schema'; // generated by openapi-typescript

class TrueFinals {
	apiKey: string;
	userId: string;
	client: Client<paths, `${string}/${string}`>;

	constructor(userId: string, userKey: string) {
		this.userId = userId;
		this.apiKey = userKey;

		const client = createClient<paths>({ baseUrl: 'https://truefinals.com/api/' });
		this.client = client;
	}

	async getTourney() {
		const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}', {
			params: {
				path: {
					tournamentID: process.env.TF_TOURNAMENT_ID
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			}
		});

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}

	async getPlayers() {
		const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}/players', {
			params: {
				path: {
					tournamentID: process.env.TF_TOURNAMENT_ID
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			}
		});

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}

	async getGames() {
		const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}/games', {
			params: {
				path: {
					tournamentID: process.env.TF_TOURNAMENT_ID
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			}
		});

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}

	async getMatchInfo(gameID: string) {
		const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}/games/{gameID}', {
			params: {
				path: {
					tournamentID: process.env.TF_TOURNAMENT_ID,
					gameID
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			}
		});

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}

	async getPlayer(playerID: string) {
		const { data, error } = await this.client.GET(
			'/v1/tournaments/{tournamentID}/players/{playerID}',
			{
				params: {
					path: {
						tournamentID: process.env.TF_TOURNAMENT_ID,
						playerID
					},
					header: {
						'x-api-key': this.apiKey,
						'x-api-user-id': this.userId
					}
				}
			}
		);

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}

	async declareWinner(
		gameId: string,
		who: 0 | 1,
		result: 'KO' | 'TO' | 'JD' | 'TKO' | 'HLD' | 'BY' | 'DQ' | 'FF' | 'T'
	) {
		await this.client.POST('/v1/tournaments/{tournamentID}/games/{gameID}', {
			params: {
				path: {
					tournamentID: process.env.TF_TOURNAMENT_ID,
					gameID: gameId
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			},
			body: {
				state: 'done',
				slots: [
					{ score: 1 - who, checkIn: 'checked_in' },
					{ score: who, checkIn: 'checked_in' }
				],
				locationID: null,
				resultAnnotation: result
			}
		});
	}
}

interface apiError {
	message: string;
	code: string;
	issues?: {
		message: string;
	}[];
}

function isApiError(response: any | apiError): response is apiError {
	if ((response as apiError).issues) {
		return true;
	}
	return false;
}

export { TrueFinals, isApiError };
