import createClient, { Client } from 'openapi-fetch';
import type { paths } from './truefinals-schema'; // generated by openapi-typescript
import pThrottle from 'p-throttle';


class TrueFinals {
	apiKey: string;
	userId: string;
	client: Client<paths, `${string}/${string}`>;

	tournaments: string[];
	activeTournament: string;

	private cachedTournaments: Awaited<ReturnType<typeof this.getTourney>>[] | null = null;
	private cachedPlayers: Awaited<ReturnType<typeof this.getPlayer>> | null = null;

	constructor(userId: string, userKey: string) {
		this.userId = userId;
		this.apiKey = userKey;

		const client = createClient<paths>({ baseUrl: 'https://truefinals.com/api/' });
		this.client = client;

		this.tournaments = process.env.TF_TOURNAMENT_IDS.split(',').map((id) => id.trim());
		this.activeTournament = this.tournaments[0];
	}

	async getAvailableTournaments() {
		if (this.cachedTournaments) {
			return this.cachedTournaments;
		}

		const tournaments = await Promise.all(
			this.tournaments.map(async (tournamentId) => {
				return await this.getTourney(tournamentId);
			})
		);
		this.cachedTournaments = tournaments;
		return tournaments;
	}

	getActiveTournament() {
		return this.activeTournament;
	}

	setActiveTournament(tournamentId: string) {
		if (this.tournaments.includes(tournamentId)) {
			this.activeTournament = tournamentId;
			this.cachedPlayers = null; // Clear player cache when tournament changes
			this.cachedTournaments = null; // Clear tournament cache as well, in case it's needed for the new tournament
		} else {
			throw new Error(`Tournament ID ${tournamentId} is not available.`);
		}
	}

	async getTourney(id: string = this.activeTournament) {
		const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}', {
			params: {
				path: {
					tournamentID: id
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			}
		});

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}

	async getPlayers() {
		if (this.cachedPlayers) {
			return this.cachedPlayers;
		}

		const returnedPlayers = [];
		for (const tournamentId of this.tournaments) {
			const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}/players', {
				params: {
					path: {
						tournamentID: tournamentId
					},
					header: {
						'x-api-key': this.apiKey,
						'x-api-user-id': this.userId
					}
				}
			});

			if (data !== undefined) {
				returnedPlayers.push(...data);
			} else {
				return error;
			}
		}
		this.cachedPlayers = returnedPlayers;
		return returnedPlayers;
	}

	async getGames() {
		const throttledGetGames = pThrottle({
			limit: 1,
			interval: 10000
		})(this.getGamesInternal.bind(this));
		return await throttledGetGames();
	}

	private async getGamesInternal() {
		const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}/games', {
			params: {
				path: {
					tournamentID: this.activeTournament
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			}
		});

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}

	async getAllGames() {
		const throttledGetGames = pThrottle({
			limit: 1,
			interval: 10000
		})(this.getAllGamesInternal.bind(this));
		return await throttledGetGames();
	}

	private async getAllGamesInternal() {
    // goes through all tournaments and gets all games
    const allGames = [];
    for (const tournamentId of this.tournaments) {
      const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}/games', {
        params: {
          path: {
            tournamentID: tournamentId
          },
          header: {
            'x-api-key': this.apiKey,
            'x-api-user-id': this.userId
          }
        }
      });
      if (data !== undefined) {
        allGames.push(...data);
      } else {
        return error;
      }
    }
    return allGames;
	}

	async getMatchInfo(gameID: string) {
		const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}/games/{gameID}', {
			params: {
				path: {
					tournamentID: this.activeTournament,
					gameID
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			}
		});

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}

	async getPlayer(playerID: string) {
		if (this.cachedPlayers) {
			const player = this.cachedPlayers.find((p) => p.id === playerID);
			if (player) {
				return player;
			}
		}

		const { data, error } = await this.client.GET(
			'/v1/tournaments/{tournamentID}/players/{playerID}',
			{
				params: {
					path: {
						tournamentID: this.activeTournament,
						playerID
					},
					header: {
						'x-api-key': this.apiKey,
						'x-api-user-id': this.userId
					}
				}
			}
		);

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}

	async markGameActive(gameId: string, tournamentId: string = this.activeTournament) {
		const { error } = await this.client.POST('/v1/tournaments/{tournamentID}/games/{gameID}', {
			params: {
				path: {
					tournamentID: tournamentId,
					gameID: gameId
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			},
			body: {
				state: 'active',
				slots: [
					{ score: 0, checkIn: 'checked_in' },
					{ score: 0, checkIn: 'checked_in' }
				],
				locationID: null,
				resultAnnotation: null
			}
		});
		if (error !== undefined) {
			console.error(error);
		}
	}

	async declareWinner(
		gameId: string,
		who: 0 | 1,
		result: 'KO' | 'TO' | 'JD' | 'TKO' | 'HLD' | 'BY' | 'DQ' | 'FF' | 'T',
		tournamentId: string = this.activeTournament
	) {
		console.log(gameId);
		const { error } = await this.client.POST('/v1/tournaments/{tournamentID}/games/{gameID}', {
			params: {
				path: {
					tournamentID: tournamentId,
					gameID: gameId
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			},
			body: {
				state: 'active',
				slots: [
					{ score: 1 - who, checkIn: 'not_ready' },
					{ score: who, checkIn: 'not_ready' }
				],
				locationID: null,
				resultAnnotation: result
			}
		});
		if (error !== undefined) {
			console.error(error);
		}
	}
}

interface apiError {
	message: string;
	code: string;
	issues?: {
		message: string;
	}[];
}

function isApiError(response: unknown | apiError): response is apiError {
	if ((response as apiError).issues) {
		return true;
	}
	return false;
}

export { TrueFinals, isApiError };
