import createClient, { Client } from 'openapi-fetch';
import type { paths } from './truefinals-schema'; // generated by openapi-typescript

class TrueFinals {
	apiKey: string;
	userId: string;
	client: Client<paths, `${string}/${string}`>;

	constructor(userId: string, userKey: string) {
		this.userId = userId;
		this.apiKey = userKey;

		const client = createClient<paths>({ baseUrl: 'https://truefinals.com/api/' });
		this.client = client;
	}

	async getTourney() {
		const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}', {
			params: {
				path: {
					tournamentID: process.env.TF_TOURNAMENT_ID
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			}
		});

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}

	async getPlayers() {
		const { data, error } = await this.client.GET('/v1/tournaments/{tournamentID}/players', {
			params: {
				path: {
					tournamentID: process.env.TF_TOURNAMENT_ID
				},
				header: {
					'x-api-key': this.apiKey,
					'x-api-user-id': this.userId
				}
			}
		});

		if (data !== undefined) {
			return data;
		} else {
			return error;
		}
	}
}

export { TrueFinals };
